# To add service: add column to shows table & add it to constant in shows model
# Change prices of services in shows model

# Network.create(name:"ABC", image:"abc.png")
# networkvar.shows.create(name:"Shark Tank", hulu:true, netflix:false, itunes:0, amazon:2.59)

# User.create(email:"",password:"")

ae = Network.create(name:"A&E", image:"network/a&e.png")
abc = Network.create(name:"ABC", image:"network/abc.png")
abcfamily = Network.create(name:"ABC Family", image:"network/abcfamily.png")
amc = Network.create(name:"AMC", image:"network/amc.png")
animalplanet = Network.create(name:"Animal Planet", image:"network/animalplanet.png")
bbc = Network.create(name:"BBC America", image:"network/bbc.png")
bet = Network.create(name:"BET", image:"network/bet.png")
bio = Network.create(name:"Bio", image:"network/bio.png")
bravo = Network.create(name:"Bravo", image:"network/bravo.png")
cartoonnetwork = Network.create(name:"Cartoon Network", image:"network/cartoonnetwork.png")
cbs = Network.create(name:"CBS", image:"network/cbs.png")
cinemax = Network.create(name:"Cinemax", image:"network/cinemax.png")
cmt = Network.create(name:"CMT", image:"network/cmt.png")
cnbc = Network.create(name:"CNBC", image:"network/cnbc.png")
comedy = Network.create(name:"Comedy Central", image:"network/comedy.png")
cw = Network.create(name:"CW", image:"network/cw.png")
discoverychannel = Network.create(name:"Discovery Channel", image:"network/discoverychannel.png")
disney = Network.create(name:"Disney", image:"network/disney.png")
e = Network.create(name:"E!", image:"network/e!.png")
encore = Network.create(name:"Encore", image:"network/encore.png")
espn = Network.create(name:"ESPN", image:"network/espn.png")
esquire = Network.create(name:"Esquire", image:"network/esquire.png")
food = Network.create(name:"Food Network", image:"network/food.png")
fox = Network.create(name:"Fox", image:"network/fox.png")
fx = Network.create(name:"FX", image:"network/fx.png")
hallmark = Network.create(name:"Hallmark Channel", image:"network/hallmark.png")
hbo = Network.create(name:"HBO", image:"network/hbo.png")
hgtv = Network.create(name:"HGTV", image:"network/hgtv.png")
history = Network.create(name:"History", image:"network/history.png")
hub = Network.create(name:"Hub", image:"network/hub.png")
hulu = Network.create(name:"Hulu", image:"network/hulu.png")
id = Network.create(name:"ID", image:"network/id.png")
ifc = Network.create(name:"IFC", image:"network/ifc.png")
ion = Network.create(name:"Ion", image:"network/ion.png")
lifetime = Network.create(name:"Lifetime", image:"network/lifetime.png")
mtv = Network.create(name:"MTV", image:"network/mtv.png")
nationalgeographic = Network.create(name:"National Geographic", image:"network/nationalgeographic.png")
nbc = Network.create(name:"NBC", image:"network/nbc.png")
netflix = Network.create(name:"Netflix", image:"network/netflix.png")
nick = Network.create(name:"Nick", image:"network/nick.png")
own = Network.create(name:"OWN", image:"network/own.png")
oxygen = Network.create(name:"Oxygen", image:"network/oxygen.png")
pbs = Network.create(name:"PBS", image:"network/pbs.png")
reelz = Network.create(name:"Reelz", image:"network/reelz.png")
science = Network.create(name:"Science", image:"network/science.png")
showtime = Network.create(name:"Showtime", image:"network/showtime.png")
spike = Network.create(name:"Spike", image:"network/spike.png")
starz = Network.create(name:"Starz", image:"network/starz.png")
sundance = Network.create(name:"Sundance", image:"network/sundance.png")
syfy = Network.create(name:"SyFy", image:"network/syfy.png")
tbs = Network.create(name:"TBS", image:"network/tbs.png")
tlc = Network.create(name:"TLC", image:"network/tlc.png")
tnt = Network.create(name:"TNT", image:"network/tnt.png")
travel = Network.create(name:"Travel Channel", image:"network/travel.png")
trutv = Network.create(name:"Tru TV", image:"network/trutv.png")
tvland = Network.create(name:"TV Land", image:"network/tvland.png")
usa = Network.create(name:"USA", image:"network/usa.png")
vh1 = Network.create(name:"VH1", image:"network/vh1.png")
we = Network.create(name:"WE", image:"network/we.png")
wgn = Network.create(name:"WGN", image:"network/wgn.png")
