# Change prices of services in shows model
# To add service: add column to shows table & add it to constant in shows model

# Network.create(name:"ABC", image:"abc.png")
# networkvar.shows.create(name:"Shark Tank", hulu:true, netflix:false, itunes:0, amazon:2.59)
# User.create(email:"",password:"")

abc = Network.create(name:"ABC", image:"network/abc.png")
abc_family = Network.create(name:"ABC Family", image:"network/abcfamily.png")
ae = Network.create(name:"A&E", image:"network/a&e.png")
amc = Network.create(name:"AMC", image:"network/amc.png")
animal_planet = Network.create(name:"Animal Planet", image:"network/animalplanet.png")
bbc = Network.create(name:"BBC America", image:"network/bbc.png")
bet = Network.create(name:"BET", image:"network/bet.png")
bravo = Network.create(name:"Bravo", image:"network/bravo.png")
cartoon_network = Network.create(name:"Cartoon Network", image:"network/cartoonnetwork.png")
cbs = Network.create(name:"CBS", image:"network/cbs.png")
cinemax = Network.create(name:"Cinemax", image:"network/cinemax.png")
cmt = Network.create(name:"CMT", image:"network/cmt.png")
cnbc = Network.create(name:"CNBC", image:"network/cnbc.png")
comedy = Network.create(name:"Comedy Central", image:"network/comedy.png")
cw = Network.create(name:"CW", image:"network/cw.png")
discovery = Network.create(name:"Discovery Channel", image:"network/discoverychannel.png")
disney = Network.create(name:"Disney", image:"network/disney.png")
e = Network.create(name:"E!", image:"network/e!.png")
encore = Network.create(name:"Encore", image:"network/encore.png")
espn = Network.create(name:"ESPN", image:"network/espn.png")
esquire = Network.create(name:"Esquire", image:"network/esquire.png")
food = Network.create(name:"Food Network", image:"network/food.png")
fox = Network.create(name:"Fox", image:"network/fox.png")
fx = Network.create(name:"FX", image:"network/fx.png")
fyi = Network.create(name:"FYI", image:"network/fyi.png")
hallmark = Network.create(name:"Hallmark Channel", image:"network/hallmark.png")
hbo = Network.create(name:"HBO", image:"network/hbo.png")
hgtv = Network.create(name:"HGTV", image:"network/hgtv.png")
history = Network.create(name:"History", image:"network/history.png")
hub = Network.create(name:"Hub", image:"network/hub.png")
hulu = Network.create(name:"Hulu", image:"network/hulu.png")
id = Network.create(name:"ID", image:"network/id.png")
ifc = Network.create(name:"IFC", image:"network/ifc.png")
ion = Network.create(name:"Ion", image:"network/ion.png")
lifetime = Network.create(name:"Lifetime", image:"network/lifetime.png")
mtv = Network.create(name:"MTV", image:"network/mtv.png")
national_geographic = Network.create(name:"National Geographic", image:"network/nationalgeographic.png")
nbc = Network.create(name:"NBC", image:"network/nbc.png")
netflix = Network.create(name:"Netflix", image:"network/netflix.png")
nick = Network.create(name:"Nick", image:"network/nick.png")
own = Network.create(name:"OWN", image:"network/own.png")
oxygen = Network.create(name:"Oxygen", image:"network/oxygen.png")
pbs = Network.create(name:"PBS", image:"network/pbs.png")
reelz = Network.create(name:"Reelz", image:"network/reelz.png")
science = Network.create(name:"Science", image:"network/science.png")
showtime = Network.create(name:"Showtime", image:"network/showtime.png")
spike = Network.create(name:"Spike", image:"network/spike.png")
starz = Network.create(name:"Starz", image:"network/starz.png")
sundance = Network.create(name:"Sundance", image:"network/sundance.png")
syfy = Network.create(name:"SyFy", image:"network/syfy.png")
tbs = Network.create(name:"TBS", image:"network/tbs.png")
tlc = Network.create(name:"TLC", image:"network/tlc.png")
tnt = Network.create(name:"TNT", image:"network/tnt.png")
travel = Network.create(name:"Travel Channel", image:"network/travel.png")
trutv = Network.create(name:"Tru TV", image:"network/trutv.png")
tv_land = Network.create(name:"TV Land", image:"network/tvland.png")
usa = Network.create(name:"USA", image:"network/usa.png")
vh1 = Network.create(name:"VH1", image:"network/vh1.png")
we = Network.create(name:"WE", image:"network/we.png")
wgn = Network.create(name:"WGN", image:"network/wgn.png")

abc.shows.create(name:"101 Ways to Leave a Game Show", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Agent Carter", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Agents of S.H.I.E.L.D.", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Bachelor in Paradise", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Bet on Your Baby", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Black-ish", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Castle", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Cristela", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Dancing with the Stars", hulu:false, netflix:false, itunes:2.99, amazon:3.99)
abc.shows.create(name:"Expedition Impossible", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Extreme Makeover: Home Edition", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Extreme Makeover: Weight Loss Edition", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Family Tools", hulu:false, netflix:false, itunes:0, amazon:0)
abc.shows.create(name:"Final Witness", hulu:false, netflix:false, itunes:0, amazon:0)
abc.shows.create(name:"Forever", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
abc.shows.create(name:"General Hospital", hulu:true, netflix:true, itunes:2.99, amazon:3.99)
abc.shows.create(name:"Grey's Anatomy", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Here Come the Newlyweds", hulu:false, netflix:false, itunes:0, amazon:1.99)
abc.shows.create(name:"How to Get Away with Murder", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
abc.shows.create(name:"I Survived a Japanese Game Show", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Jimmy Kimmel Live!", hulu:true, netflix:false, itunes:2.99, amazon:2.99)
abc.shows.create(name:"Karaoke Battle USA", hulu:false, netflix:false, itunes:2.99, amazon:2.99)
abc.shows.create(name:"Last Man Standing", hulu:true, netflix:false, itunes:2.99, amazon:22.89)
abc.shows.create(name:"Mistresses", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Modern Family", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Nashville", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Nightline Prime", hulu:true, netflix:false, itunes:0, amazon:0)
abc.shows.create(name:"NY Med", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Once Upon a Time", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Primetime Live", hulu:true, netflix:false, itunes:2.99, amazon:0.89)
abc.shows.create(name:"Resurrection", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Revenge", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Scandal", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Shaq Vs.", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Shark Tank", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
abc.shows.create(name:"Sing Your Face Off", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
abc.shows.create(name:"The Bachelor", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
abc.shows.create(name:"The Bachelorette", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
abc.shows.create(name:"The Glass House", hulu:true, netflix:true, itunes:2.99, amazon:3.99)
abc.shows.create(name:"The Goldbergs", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
abc.shows.create(name:"The Middle", hulu:true, netflix:true, itunes:2.99, amazon:0)
abc.shows.create(name:"The Quest", hulu:true, netflix:true, itunes:2.99, amazon:3.22)
abc.shows.create(name:"The Taste", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
abc.shows.create(name:"Wife Swap", hulu:true, netflix:false, itunes:2.99, amazon:0)
abc.shows.create(name:"Wipeout", hulu:true, netflix:false, itunes:2.99, amazon:0)
abc_family.shows.create(name:"Baby Daddy", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
abc_family.shows.create(name:"Chasing Life", hulu:true, netflix:false, itunes:2.99, amazon:1.89)
abc_family.shows.create(name:"Melissa & Joey", hulu:true, netflix:false, itunes:0, amazon:1.99)
abc_family.shows.create(name:"Pretty Little Liars", hulu:true, netflix:false, itunes:2.99, amazon:0)
abc_family.shows.create(name:"Switched at Birth", hulu:true, netflix:true, itunes:2.99, amazon:1.89)
abc_family.shows.create(name:"The Fosters", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
abc_family.shows.create(name:"The Vineyard", hulu:true, netflix:false , itunes:2.99, amazon:2.01)
abc_family.shows.create(name:"Young & Hungry", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
ae.shows.create(name:"American Hoggers", hulu:true, netflix:false, itunes:2.99, amazon:18.99)
ae.shows.create(name:"Barter Kings", hulu:true, netflix:false, itunes:2.99, amazon:24.99)
ae.shows.create(name:"Bates Motel", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
ae.shows.create(name:"Beyond Scared Straight", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
ae.shows.create(name:"Cajun Justice", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
ae.shows.create(name:"Duck Dynasty", hulu:true, netflix:true, itunes:2.99, amazon:2.99)
ae.shows.create(name:"Modern Dads", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
ae.shows.create(name:"Modern Marvels", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
ae.shows.create(name:"Paranormal State", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
ae.shows.create(name:"Parking Wars", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
ae.shows.create(name:"Psychic Tia", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
ae.shows.create(name:"Relapse", hulu:true, netflix:false, itunes:2.99, amazon:3.99)
ae.shows.create(name:"Sell This House: Extreme", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
ae.shows.create(name:"Shipping Wars", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
ae.shows.create(name:"Storage Wars", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
ae.shows.create(name:"Storage Wars: New York", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
ae.shows.create(name:"Storage Wars: Texas", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
ae.shows.create(name:"The First 48", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
ae.shows.create(name:"The Governor's Wife", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
ae.shows.create(name:"Wahlburgers", hulu:true, netflix:true, itunes:2.99, amazon:3.1)
amc.shows.create(name:"Comic Book Men", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
amc.shows.create(name:"Freakshow", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
amc.shows.create(name:"Halt and Catch Fire", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
amc.shows.create(name:"Hell on Wheels", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
amc.shows.create(name:"Mad Men", hulu:true, netflix:true, itunes:2.99, amazon:1.67)
amc.shows.create(name:"Owner's Manual", hulu:false, netflix:false, itunes:0, amazon:1.99)
amc.shows.create(name:"Showville", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
amc.shows.create(name:"Small Town Security", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
amc.shows.create(name:"Talking Dead", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
amc.shows.create(name:"The Pitch", hulu:false , netflix:false , itunes:2.99, amazon:2.79)
amc.shows.create(name:"The Walking Dead", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
amc.shows.create(name:"Turn", hulu:true, netflix:true, itunes:2.99, amazon:2.99)
animal_planet.shows.create(name:"Alaska Gold Diggers", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
animal_planet.shows.create(name:"Confessions: Animal Hoarding", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
animal_planet.shows.create(name:"Dogs 101", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
animal_planet.shows.create(name:"Finding Bigfoot", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
animal_planet.shows.create(name:"Hillbilly Handfishin", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
animal_planet.shows.create(name:"It's Me or the Dog", hulu:false, netflix:false, itunes:2.99, amazon:0.99)
animal_planet.shows.create(name:"Monsters Inside Me", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
animal_planet.shows.create(name:"My Cat From Hell", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
animal_planet.shows.create(name:"North Woods Law", hulu:false, netflix:false, itunes:2.99, amazon:2.99)
animal_planet.shows.create(name:"Pit Boss", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
animal_planet.shows.create(name:"Rat Busters NYC", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
animal_planet.shows.create(name:"River Monsters", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
animal_planet.shows.create(name:"Tanked", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
animal_planet.shows.create(name:"Whale Wars", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
bbc.shows.create(name:"Almost Royal", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
bbc.shows.create(name:"Chef Race: UK vs U.S.", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
bbc.shows.create(name:"Fleming: The Man Who Would Be Bond", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
bbc.shows.create(name:"Intruders", hulu:false, netflix:false, itunes:2.99, amazon:2.96)
bbc.shows.create(name:"Orphan Black", hulu:true, netflix:true, itunes:2.99, amazon:0)
bbc.shows.create(name:"Richard Hammond's Crash Course", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
bbc.shows.create(name:"The Nerdist", hulu:false , netflix:false , itunes:2.99, amazon:3.97)
bbc.shows.create(name:"Top Gear", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
bet.shows.create(name:"Being Mary Jane", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
bet.shows.create(name:"Let's Stay Together", hulu:true, netflix:false, itunes:2.99, amazon:2.09)
bet.shows.create(name:"Real Husbands of Hollywood", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
bet.shows.create(name:"Reed Between the Lines", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
bet.shows.create(name:"The Family Crews", hulu:false, netflix:true, itunes:2.99, amazon:0)
bet.shows.create(name:"The Game", hulu:true, netflix:true, itunes:2.99, amazon:2.99)
bet.shows.create(name:"Tiny & Toya", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"100 Days of Summer", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Around the World In 80 Plates", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Below Deck", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Chef Robl&eacute; & Co.", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"City Girl Diaries", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Flipping Out", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Gallery Girls", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Giuliana & Bill", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Inside the Actors Studio", hulu:true, netflix:true, itunes:2.99, amazon:8.64)
bravo.shows.create(name:"Interior Therapy with Jeff Lewis", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"It's a Brad Brad World", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Jerseylicious", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Kell on Earth", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Kimora: House of Fab", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Ladies of London", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Life After Top Chef", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"LOLwork", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Love Broker", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Married to Medicine", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Million Dollar Listing New York", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Million Dollar Listing", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Millionaire Matchmaker", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Newlyweds: The First Year", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Platinum Hit", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Project Runway", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Rocco's Dinner Party", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Ruby", hulu:false, netflix:false, itunes:2.99, amazon:0)
bravo.shows.create(name:"Shahs of Sunset", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Shear Genius", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Southern Charm", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Tabatha's Salon Takeover", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Tabitha Takes Over", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Tamra's OC Wedding", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"The Kandi Factory", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"The Rachel Zoe Project", hulu:true, netflix:true, itunes:2.99, amazon:11.94)
bravo.shows.create(name:"The Real Housewives of Atlanta", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"The Real Housewives of Beverly Hills", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"The Real Housewives of Miami", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"The Real Housewives of New Jersey", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"The Real Housewives of New York City", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"The Real Housewives of Orange County", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Thintervention with Jackie Warner", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Tia & Tamera", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Top Chef Masters", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Top Chef", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
bravo.shows.create(name:"Watch What Happens: Live", hulu:true, netflix:false, itunes:2.99, amazon:2.54)
bravo.shows.create(name:"XOX Betsey Johnson", hulu:false, netflix:false, itunes:2.99, amazon:0)
cartoon_network.shows.create(name:"Adventure Time", hulu:false, netflix:true, itunes:2.99, amazon:1.89)
cartoon_network.shows.create(name:"Aqua Teen Hunger Force", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"Ben 10: Omniverse", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"Ben 10: Ultimate Alien", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"Beware the Batman", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"Black Dynamite", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"Black Jesus", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"Check It Out with Dr. Steve Brule", hulu:true, netflix:true, itunes:2.99, amazon:2.43)
cartoon_network.shows.create(name:"Childrens Hospital", hulu:true, netflix:true, itunes:2.99, amazon:2.99)
cartoon_network.shows.create(name:"China, IL", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"Destroy Build Destroy", hulu:false, netflix:false, itunes:2.99, amazon:0)
cartoon_network.shows.create(name:"Dragons: Riders of Berk", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"Dude, What Would Happen", hulu:false, netflix:false, itunes:2.99, amazon:0)
cartoon_network.shows.create(name:"Eagleheart", hulu:false, netflix:false, itunes:2.99, amazon:3.94)
cartoon_network.shows.create(name:"Generator Rex", hulu:false, netflix:false, itunes:2.99, amazon:0.65)
cartoon_network.shows.create(name:"Hot Wheels: Battle Force 5", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"Incredible Crew", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"Level Up", hulu:true, netflix:false, itunes:2.99, amazon:2.24)
cartoon_network.shows.create(name:"Loiter Squad", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"Mad", hulu:true, netflix:true, itunes:2.99, amazon:0)
cartoon_network.shows.create(name:"Metalocalypse", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"Mike Tyson Mysteries", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"Newsreaders", hulu:false, netflix:false, itunes:2.99, amazon:0.99)
cartoon_network.shows.create(name:"NTSF:SD:SUV::", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"Off the Air", hulu:false, netflix:false, itunes:2.99, amazon:0)
cartoon_network.shows.create(name:"Over the Garden Wall", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"Rick and Morty", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"Robot Chicken", hulu:true, netflix:true, itunes:2.99, amazon:9)
cartoon_network.shows.create(name:"Secret Mountain Fort Awesome", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"Squidbillies", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"Steven Universe", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"Superjail!", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"Teen Titans Go!", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"The Amazing World of Gumball", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"The Boondocks", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"The Garfield Show", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cartoon_network.shows.create(name:"The Heart, She Holler", hulu:false , netflix:false , itunes:2.99, amazon:0)
cartoon_network.shows.create(name:"The High Fructose Adventures of Annoying Orange", hulu:true, netflix:false , itunes:2.99, amazon:3.58)
cartoon_network.shows.create(name:"The Looney Tunes Show", hulu:false , netflix:true, itunes:2.99, amazon:6.49)
cartoon_network.shows.create(name:"The Venture Bros.", hulu:true, netflix:true, itunes:2.99, amazon:2.79)
cartoon_network.shows.create(name:"Tim and Eric Awesome Show, Great Job!", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"2 Broke Girls", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"48 Hours Mystery", hulu:true, netflix:false, itunes:1.99, amazon:1.99)
cbs.shows.create(name:"60 Minutes", hulu:false, netflix:true, itunes:1.99, amazon:0)
cbs.shows.create(name:"Big Brother", hulu:false, netflix:true, itunes:2.99, amazon:0.08)
cbs.shows.create(name:"Blue Bloods", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"C.S.I.", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"Criminal Minds", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"Dino Squad", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"Dogs in the City", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"Elementary", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"Extant", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"Hallmark Hall of Fame", hulu:false, netflix:false, itunes:0, amazon:0)
cbs.shows.create(name:"Hawaii Five-0", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"I Get That a Lot", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"Late Show with David Letterman", hulu:false, netflix:false, itunes:0, amazon:2.98)
cbs.shows.create(name:"Live to Dance", hulu:true, netflix:true, itunes:2.99, amazon:3.28)
cbs.shows.create(name:"Madam Secretary", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"Mike & Molly", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"Mom", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"NCIS", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"NCIS: Los Angeles", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"NCIS: New Orleans", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"Person of Interest", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"Same Name", hulu:false, netflix:false, itunes:0, amazon:0)
cbs.shows.create(name:"Scorpion", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"Stalker", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"Survivor", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"The Amazing Race", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"The American Baking Competition", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
cbs.shows.create(name:"The Big Bang Theory", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cbs.shows.create(name:"The Good Wife", hulu:true, netflix:true, itunes:2.99, amazon:0)
cbs.shows.create(name:"The Late Late Show with Craig Ferguson", hulu:false , netflix:false , itunes:0, amazon:0)
cbs.shows.create(name:"The McCarthys", hulu:true, netflix:false , itunes:2.99, amazon:2.85)
cbs.shows.create(name:"The Mentalist", hulu:true, netflix:true, itunes:2.99, amazon:4.84)
cbs.shows.create(name:"The Millers", hulu:true, netflix:false , itunes:2.99, amazon:11.14)
cbs.shows.create(name:"Two and a Half Men", hulu:true, netflix:true, itunes:2.99, amazon:2.94)
cbs.shows.create(name:"Under the Dome", hulu:false, netflix:true, itunes:2.99, amazon:2.64)
cbs.shows.create(name:"Undercover Boss", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cinemax.shows.create(name:"Banshee", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
cinemax.shows.create(name:"Femme Fatales", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
cinemax.shows.create(name:"Strike Back", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cinemax.shows.create(name:"The Knick", hulu:false , netflix:false , itunes:2.99, amazon:0)
cmt.shows.create(name:"Cheer", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
cmt.shows.create(name:"Guntucky", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
cmt.shows.create(name:"Redneck Rehab", hulu:false, netflix:false, itunes:0, amazon:0.99)
cmt.shows.create(name:"Sweet Home Alabama", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cmt.shows.create(name:"Top Secret Recipe", hulu:true, netflix:false, itunes:2.99, amazon:2.85)
cnbc.shows.create(name:"American Greed", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
cnbc.shows.create(name:"The Profit", hulu:true, netflix:false , itunes:0, amazon:0.01)
comedy.shows.create(name:"Brickleberry", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
comedy.shows.create(name:"Broad City", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
comedy.shows.create(name:"Drunk History", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
comedy.shows.create(name:"Gabriel Iglesias Presents Stand-Up Revolution", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
comedy.shows.create(name:"Inside Amy Schumer", hulu:true, netflix:true, itunes:2.99, amazon:24.99)
comedy.shows.create(name:"Key and Peele", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
comedy.shows.create(name:"Kroll Show", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
comedy.shows.create(name:"Nathan for You", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
comedy.shows.create(name:"Review", hulu:false, netflix:true, itunes:0, amazon:1.99)
comedy.shows.create(name:"South Park", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
comedy.shows.create(name:"The Burn", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
comedy.shows.create(name:"The Colbert Report", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
comedy.shows.create(name:"The Daily Show", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
comedy.shows.create(name:"The Half Hour", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
comedy.shows.create(name:"The Meltdown with Jonah and Kumail", hulu:true, netflix:false , itunes:0, amazon:0)
comedy.shows.create(name:"Tosh.0", hulu:true, netflix:false, itunes:2.99, amazon:0)
comedy.shows.create(name:"TripTank", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
comedy.shows.create(name:"Workaholics", hulu:true, netflix:true, itunes:2.99, amazon:0)
cw.shows.create(name:"America's Next Top Model", hulu:false, netflix:false, itunes:0, amazon:3.99)
cw.shows.create(name:"Arrow", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cw.shows.create(name:"Beauty and the Beast", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
cw.shows.create(name:"Capture", hulu:false, netflix:false, itunes:0, amazon:0)
cw.shows.create(name:"Hart of Dixie", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cw.shows.create(name:"Jane the Virgin", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
cw.shows.create(name:"Johnny Test", hulu:false, netflix:false, itunes:2.99, amazon:0.61)
cw.shows.create(name:"Masters of Illusion", hulu:true, netflix:false, itunes:2.99, amazon:0)
cw.shows.create(name:"Perfect Score", hulu:false, netflix:true, itunes:2.99, amazon:2.99)
cw.shows.create(name:"Reign", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
cw.shows.create(name:"Remodeled", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
cw.shows.create(name:"Supernatural", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cw.shows.create(name:"The 100", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
cw.shows.create(name:"The Catalina", hulu:true, netflix:true, itunes:2.99, amazon:2.99)
cw.shows.create(name:"The Flash", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cw.shows.create(name:"The Originals", hulu:true, netflix:true, itunes:2.99, amazon:9.59)
cw.shows.create(name:"The Vampire Diaries", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
cw.shows.create(name:"Whose Line Is It Anyway?", hulu:true, netflix:true, itunes:2.99, amazon:5.49)
discovery.shows.create(name:"After the Catch", hulu:false, netflix:false, itunes:1.99, amazon:1.99)
discovery.shows.create(name:"Airplane Repo", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
discovery.shows.create(name:"Alaska: the Last Frontier", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
discovery.shows.create(name:"American Chopper: Senior vs. Junior", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
discovery.shows.create(name:"Amish Mafia", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
discovery.shows.create(name:"Auction Kings", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
discovery.shows.create(name:"Bering Sea Gold", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
discovery.shows.create(name:"Bering Sea Gold: Under the Ice", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
discovery.shows.create(name:"Chasing Classic Cars", hulu:false, netflix:false, itunes:2.99, amazon:28.89)
discovery.shows.create(name:"Curiosity: The Questions of Life", hulu:false, netflix:false, itunes:2.99, amazon:2.99)
discovery.shows.create(name:"Dual Survival", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
discovery.shows.create(name:"Fast n Loud", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
discovery.shows.create(name:"Ghost Lab", hulu:false, netflix:false, itunes:2.99, amazon:3.99)
discovery.shows.create(name:"Gold Rush Alaska", hulu:false, netflix:false, itunes:2.99, amazon:2.42)
discovery.shows.create(name:"Hogs Gone Wild", hulu:false, netflix:false, itunes:0, amazon:1.99)
discovery.shows.create(name:"How the Universe Works", hulu:false, netflix:true, itunes:2.99, amazon:2.69)
discovery.shows.create(name:"Howe & Howe Tech", hulu:false, netflix:false, itunes:2.99, amazon:4)
discovery.shows.create(name:"I Didn't Know I Was Pregnant", hulu:false, netflix:false, itunes:0, amazon:2.99)
discovery.shows.create(name:"I'm Pregnant and ...", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
discovery.shows.create(name:"Klondike", hulu:true, netflix:true, itunes:2.99, amazon:2.54)
discovery.shows.create(name:"Mutant Planet", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
discovery.shows.create(name:"MythBusters", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
discovery.shows.create(name:"Naked and Afraid", hulu:true, netflix:false, itunes:2.99, amazon:0)
discovery.shows.create(name:"Oddities", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
discovery.shows.create(name:"Siberian Cut", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
discovery.shows.create(name:"Sons of Guns", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
discovery.shows.create(name:"The Deadliest Catch", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
discovery.shows.create(name:"The Devils Ride", hulu:false , netflix:false , itunes:2.99, amazon:1.99)
discovery.shows.create(name:"Unchained Reaction", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
discovery.shows.create(name:"Untold Stories of the ER", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Austin & Ally", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Code: 9", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Crash & Bernstein", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Dog with a Blog", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Evermoor", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Fish Hooks", hulu:false, netflix:false, itunes:0, amazon:0)
disney.shows.create(name:"Girl Meets World", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Gravity Falls", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Handy Manny", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Hulk and the Agents of S.M.A.S.H.", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
disney.shows.create(name:"I Didn't Do It", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Imagination Movers", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Jessie", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Kick Buttowski: Suburban Daredevil", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Kickin' It", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Kid vs. Kat", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Kirby Buckets", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Lab Rats", hulu:false, netflix:false, itunes:2.99, amazon:1.89)
disney.shows.create(name:"Liv & Maddie", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Marvel's Avengers Assemble", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Max Steel", hulu:false, netflix:false, itunes:2.99, amazon:1.89)
disney.shows.create(name:"Mighty Med", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
disney.shows.create(name:"My Babysitter's a Vampire", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Phineas and Ferb", hulu:false, netflix:false, itunes:2.99, amazon:2.92)
disney.shows.create(name:"Randy Cunningham: 9th Grade Ninja", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
disney.shows.create(name:"SlugTerra", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
disney.shows.create(name:"So Random!", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Sofia the First", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
disney.shows.create(name:"Star Wars Rebels", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
disney.shows.create(name:"Ultimate Spider-Man", hulu:true, netflix:true, itunes:2.99, amazon:2.74)
disney.shows.create(name:"Wander Over Yonder", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
disney.shows.create(name:"Xiaolin Chronicles", hulu:false, netflix:true, itunes:2.99, amazon:2.75)
e.shows.create(name:"Bridalplasty", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
e.shows.create(name:"Burning Love", hulu:true, netflix:true, itunes:2.99, amazon:2.99)
e.shows.create(name:"Holly's World", hulu:false, netflix:false, itunes:2.99, amazon:10.64)
e.shows.create(name:"Keeping Up with the Kardashians", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
e.shows.create(name:"Married to Jonas", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
e.shows.create(name:"Opening Act", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
e.shows.create(name:"Total Divas", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
encore.shows.create(name:"Titanic: Blood & Steel", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
espn.shows.create(name:"30 for 30", hulu:false, netflix:true, itunes:4.99, amazon:2.99)
espn.shows.create(name:"Nine for IX", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
esquire.shows.create(name:"The Getaway", hulu:true, netflix:true, itunes:2.99, amazon:2.99)
food.shows.create(name:"24 Hour Restaurant Battle", hulu:false, netflix:false, itunes:0, amazon:1.99)
food.shows.create(name:"Barefoot Contessa", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
food.shows.create(name:"Chopped", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
food.shows.create(name:"Cupcake Wars", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
food.shows.create(name:"Diners, Drive-ins and Dives", hulu:true, netflix:false, itunes:2.99, amazon:8.88)
food.shows.create(name:"Extreme Chef", hulu:false, netflix:false, itunes:0, amazon:0)
food.shows.create(name:"Extreme Cuisine with Jeff Corwin", hulu:false, netflix:false, itunes:0, amazon:0)
food.shows.create(name:"Guy's Grocery Games", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
food.shows.create(name:"Iron Chef America", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
food.shows.create(name:"Restaurant Stakeout", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
food.shows.create(name:"The Next Food Network Star", hulu:true, netflix:false , itunes:2.99, amazon:0.01)
food.shows.create(name:"Worst Cooks in America", hulu:false, netflix:false, itunes:2.99, amazon:5)
fox.shows.create(name:"24", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
fox.shows.create(name:"American Idol", hulu:true, netflix:true, itunes:2.99, amazon:3.99)
fox.shows.create(name:"Are You Smarter Than a 5th Grader?", hulu:false, netflix:false, itunes:2.99, amazon:0)
fox.shows.create(name:"Axe Cop", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
fox.shows.create(name:"Bob's Burgers", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
fox.shows.create(name:"Bones", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
fox.shows.create(name:"Brooklyn Nine-Nine", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
fox.shows.create(name:"Cops", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
fox.shows.create(name:"Cosmos: A SpaceTime Odyssey", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
fox.shows.create(name:"Dead Boss", hulu:false, netflix:false, itunes:2.99, amazon:2.45)
fox.shows.create(name:"Family Guy", hulu:true, netflix:true, itunes:2.99, amazon:2.92)
fox.shows.create(name:"Glee", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
fox.shows.create(name:"Gotham", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
fox.shows.create(name:"Gracepoint", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
fox.shows.create(name:"Hell's Kitchen", hulu:false, netflix:true, itunes:2.99, amazon:2.99)
fox.shows.create(name:"High School USA!", hulu:true, netflix:true, itunes:2.99, amazon:0.25)
fox.shows.create(name:"Hotel Hell", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
fox.shows.create(name:"In the Flow with Affion Crockett", hulu:false, netflix:false, itunes:0, amazon:0)
fox.shows.create(name:"Junior MasterChef", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
fox.shows.create(name:"Kitchen Nightmares", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
fox.shows.create(name:"Magical DoReMi", hulu:false, netflix:false, itunes:2.99, amazon:2.99)
fox.shows.create(name:"Master Chef", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
fox.shows.create(name:"Mobbed", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
fox.shows.create(name:"Mulaney", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
fox.shows.create(name:"New Girl", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
fox.shows.create(name:"Red Band Society", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
fox.shows.create(name:"Sleepy Hollow", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
fox.shows.create(name:"So You Think You Can Dance", hulu:true, netflix:false , itunes:2.99, amazon:2)
fox.shows.create(name:"The Following", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
fox.shows.create(name:"The Goodwin Games", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
fox.shows.create(name:"The Mindy Project", hulu:true, netflix:true, itunes:2.99, amazon:2.99)
fox.shows.create(name:"The Simpsons", hulu:true, netflix:false , itunes:2.99, amazon:2.96)
fox.shows.create(name:"Winx Club", hulu:false, netflix:true, itunes:2.99, amazon:0)
fx.shows.create(name:"Ali G: Rezurection", hulu:true, netflix:false, itunes:0, amazon:0)
fx.shows.create(name:"American Horror Story", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
fx.shows.create(name:"Anger Management", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
fx.shows.create(name:"Archer", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
fx.shows.create(name:"Fargo", hulu:false, netflix:false, itunes:2.99, amazon:2.99)
fx.shows.create(name:"It's Always Sunny in Philadelphia", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
fx.shows.create(name:"Justified", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
fx.shows.create(name:"Louie", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
fx.shows.create(name:"Married", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
fx.shows.create(name:"Partners", hulu:false, netflix:false, itunes:2.99, amazon:2.99)
fx.shows.create(name:"Saint George", hulu:false, netflix:false, itunes:0, amazon:1.99)
fx.shows.create(name:"Sons of Anarchy", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
fx.shows.create(name:"The Americans", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
fx.shows.create(name:"The League", hulu:true, netflix:false , itunes:2.99, amazon:2.01)
fx.shows.create(name:"The Strain", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
fx.shows.create(name:"Tyrant", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
fx.shows.create(name:"You're the Worst", hulu:true, netflix:false, itunes:2.99, amazon:0)
fyi.shows.create(name:"Celebrity Close Calls", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
fyi.shows.create(name:"Celebrity Ghost Stories", hulu:true, netflix:false, itunes:2.99, amazon:4.99)
fyi.shows.create(name:"The UneXplained", hulu:true, netflix:true, itunes:2.99, amazon:2.32)
hallmark.shows.create(name:"Cedar Cove", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
hallmark.shows.create(name:"Signed, Sealed, Delivered", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
hallmark.shows.create(name:"When Calls the Heart", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
hbo.shows.create(name:"Boardwalk Empire", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
hbo.shows.create(name:"Curb Your Enthusiasm", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
hbo.shows.create(name:"Family Tree", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
hbo.shows.create(name:"Game of Thrones", hulu:false, netflix:false, itunes:2.99, amazon:2.75)
hbo.shows.create(name:"Getting On", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
hbo.shows.create(name:"Girls", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
hbo.shows.create(name:"Hard Knocks", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
hbo.shows.create(name:"Hello Ladies", hulu:false, netflix:false, itunes:2.99, amazon:2.98)
hbo.shows.create(name:"Last Week Tonight with John Oliver", hulu:false, netflix:false, itunes:2.99, amazon:2.02)
hbo.shows.create(name:"Looking", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
hbo.shows.create(name:"Real Time with Bill Maher", hulu:false, netflix:true, itunes:2.99, amazon:0)
hbo.shows.create(name:"Silicon Valley", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
hbo.shows.create(name:"The Comeback", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
hbo.shows.create(name:"The Leftovers", hulu:false, netflix:false , itunes:2.99, amazon:2.01)
hbo.shows.create(name:"The Newsroom", hulu:false, netflix:true, itunes:2.99, amazon:0.01)
hbo.shows.create(name:"The Ricky Gervais Show", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
hbo.shows.create(name:"True Detective", hulu:false, netflix:false, itunes:2.99, amazon:2.99)
hbo.shows.create(name:"Veep", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
hbo.shows.create(name:"Vice", hulu:false, netflix:true, itunes:2.99, amazon:2.01)
hgtv.shows.create(name:"Brother vs Brother", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
hgtv.shows.create(name:"Candice Tells All", hulu:false, netflix:false, itunes:0, amazon:0)
hgtv.shows.create(name:"Deserving Design", hulu:false, netflix:false, itunes:0, amazon:0)
hgtv.shows.create(name:"Design Star", hulu:true, netflix:true, itunes:2.99, amazon:22.75)
history.shows.create(name:"America Unearthed", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
history.shows.create(name:"America's Secret Slang", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
history.shows.create(name:"American Pickers", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
history.shows.create(name:"American Restoration", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
history.shows.create(name:"Ancient Aliens", hulu:true, netflix:true, itunes:2.99, amazon:2.99)
history.shows.create(name:"Ax Men", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
history.shows.create(name:"Counting Cars", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
history.shows.create(name:"Gangland", hulu:false, netflix:true, itunes:2.99, amazon:6)
history.shows.create(name:"How the Earth Was Made", hulu:false, netflix:true, itunes:2.99, amazon:2.35)
history.shows.create(name:"Ice Road Truckers", hulu:true, netflix:true, itunes:2.99, amazon:2.26)
history.shows.create(name:"In Search of Aliens", hulu:false, netflix:false, itunes:2.99, amazon:2.89)
history.shows.create(name:"Mankind Decoded", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
history.shows.create(name:"Modern Marvels", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
history.shows.create(name:"Mountain Men", hulu:true, netflix:true, itunes:2.99, amazon:0)
history.shows.create(name:"Only in America with Larry the Cable Guy", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
history.shows.create(name:"Pawn Stars", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
history.shows.create(name:"Swamp People", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
history.shows.create(name:"The Legend of Shelby the Swamp Man", hulu:true, netflix:true, itunes:2.99, amazon:0)
history.shows.create(name:"The Universe", hulu:true, netflix:true, itunes:2.99, amazon:0)
history.shows.create(name:"The World Wars", hulu:true, netflix:true, itunes:2.99, amazon:2.64)
history.shows.create(name:"Top Gear US", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
history.shows.create(name:"Top Shot", hulu:true, netflix:true, itunes:2.99, amazon:0)
history.shows.create(name:"Vikings", hulu:true, netflix:true, itunes:2.99, amazon:0)
hub.shows.create(name:"My Little Pony: Friendship is Magic", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
hub.shows.create(name:"The Aquabats! Super Show!", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
hub.shows.create(name:"The Haunting Hour", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
hub.shows.create(name:"Transformers: Rescue Bots", hulu:false, netflix:false, itunes:2.99, amazon:2.17)
hulu.shows.create(name:"Deadbeat", hulu:true, netflix:false, itunes:2.99, amazon:2.98)
id.shows.create(name:"Deadly Women", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
id.shows.create(name:"Surviving Evil", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
id.shows.create(name:"The Shift", hulu:true, netflix:true, itunes:0, amazon:1.65)
id.shows.create(name:"The Will", hulu:true, netflix:true, itunes:2.99, amazon:3.69)
id.shows.create(name:"Who the Bleep Did I Marry?", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
ifc.shows.create(name:"Bullet in the Face", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
ifc.shows.create(name:"Bunk", hulu:false, netflix:false, itunes:0, amazon:0)
ifc.shows.create(name:"Comedy Bang! Bang!", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
ifc.shows.create(name:"Garfunkel & Oates", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
ifc.shows.create(name:"Maron", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
ifc.shows.create(name:"Out There", hulu:true, netflix:true, itunes:2.99, amazon:0)
ifc.shows.create(name:"Portlandia", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
ifc.shows.create(name:"The Birthday Boys", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
ifc.shows.create(name:"The Spoils of Babylon", hulu:true, netflix:false , itunes:2.99, amazon:4.86)
ion.shows.create(name:"The Emeril Lagasse Show", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
lifetime.shows.create(name:"Abby's Ultimate Dance Competition", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
lifetime.shows.create(name:"America's Most Wanted", hulu:false, netflix:false, itunes:0, amazon:3.99)
lifetime.shows.create(name:"Betty White's Off Their Rockers", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
lifetime.shows.create(name:"Bring It!", hulu:true, netflix:true, itunes:2.99, amazon:2.99)
lifetime.shows.create(name:"Devious Maids", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
lifetime.shows.create(name:"Double Divas", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
lifetime.shows.create(name:"Glamour Belles", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
lifetime.shows.create(name:"Little Women: LA", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
lifetime.shows.create(name:"Million Dollar Shoppers", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
lifetime.shows.create(name:"My Haunted House", hulu:true, netflix:true, itunes:2.99, amazon:0)
lifetime.shows.create(name:"My Life is a Lifetime Movie", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
lifetime.shows.create(name:"Preachers' Daughters", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
lifetime.shows.create(name:"Pretty Wicked Moms", hulu:true, netflix:false, itunes:2.99, amazon:0)
lifetime.shows.create(name:"Project Runway All Stars", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
lifetime.shows.create(name:"Russian Dolls", hulu:false, netflix:true, itunes:2.99, amazon:2.99)
lifetime.shows.create(name:"Supermarket Superstar", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
lifetime.shows.create(name:"The Houstons: On Our Own", hulu:false , netflix:false , itunes:2.99, amazon:0)
lifetime.shows.create(name:"Under the Gunn", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
mtv.shows.create(name:"Awkward", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
mtv.shows.create(name:"Catfish: The TV Show", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
mtv.shows.create(name:"Copycat", hulu:false, netflix:false, itunes:0, amazon:0.99)
mtv.shows.create(name:"Faking It", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
mtv.shows.create(name:"Finding Carter", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
mtv.shows.create(name:"Girl Code", hulu:false, netflix:false, itunes:2.99, amazon:2.95)
mtv.shows.create(name:"Guy Code", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
mtv.shows.create(name:"Happyland", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
mtv.shows.create(name:"Hip Hop Squares", hulu:false, netflix:false, itunes:2.99, amazon:2.99)
mtv.shows.create(name:"House of Jazmin", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
mtv.shows.create(name:"Human Giant", hulu:true, netflix:true, itunes:2.99, amazon:6.75)
mtv.shows.create(name:"If You Really Knew Me", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
mtv.shows.create(name:"Made", hulu:true, netflix:true, itunes:0, amazon:1.99)
mtv.shows.create(name:"My Life as Liz", hulu:true, netflix:false, itunes:0, amazon:0)
mtv.shows.create(name:"Nitro Circus", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
mtv.shows.create(name:"NumbNuts", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
mtv.shows.create(name:"Ridiculousness", hulu:true, netflix:false, itunes:2.99, amazon:0)
mtv.shows.create(name:"Rob Dyrdek's Fantasy Factory", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
mtv.shows.create(name:"Snooki and Jwow", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
mtv.shows.create(name:"Teen Mom 2", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
mtv.shows.create(name:"Teen Wolf", hulu:true, netflix:true, itunes:2.99, amazon:0)
mtv.shows.create(name:"The Alectrix", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
mtv.shows.create(name:"The Buried Life", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
mtv.shows.create(name:"The Dudesons in America", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
mtv.shows.create(name:"The Hills", hulu:true, netflix:true, itunes:2.99, amazon:0)
mtv.shows.create(name:"The Real World", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
mtv.shows.create(name:"The Show with Vinny", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
mtv.shows.create(name:"Wake Brothers", hulu:false, netflix:false, itunes:2.99, amazon:2.95)
national_geographic.shows.create(name:"Alaska State Troopers", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
national_geographic.shows.create(name:"America's Lost Treasures", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
national_geographic.shows.create(name:"Brain Games", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
national_geographic.shows.create(name:"Church Rescue", hulu:false, netflix:false, itunes:2.99, amazon:2.93)
national_geographic.shows.create(name:"Cosmos: A SpaceTime Odyssey", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
national_geographic.shows.create(name:"Diggers", hulu:false, netflix:false, itunes:2.99, amazon:0.99)
national_geographic.shows.create(name:"Doomsday Preppers", hulu:true, netflix:false, itunes:2.99, amazon:2.99)
national_geographic.shows.create(name:"Drugs, Inc.", hulu:true, netflix:false, itunes:2.99, amazon:2.99)
national_geographic.shows.create(name:"Expedition Great White", hulu:false, netflix:false, itunes:0, amazon:1.99)
national_geographic.shows.create(name:"Family Guns", hulu:false, netflix:false, itunes:0, amazon:0)
national_geographic.shows.create(name:"Flea Man", hulu:false, netflix:false, itunes:0, amazon:0)
national_geographic.shows.create(name:"Hard Time", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
national_geographic.shows.create(name:"Known Universe", hulu:false, netflix:false, itunes:2.99, amazon:2.9)
national_geographic.shows.create(name:"Life Below Zero", hulu:true, netflix:false, itunes:2.99, amazon:2.99)
national_geographic.shows.create(name:"Locked Up Abroad", hulu:false, netflix:true, itunes:2.99, amazon:0)
national_geographic.shows.create(name:"National Geographic Explorer", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
national_geographic.shows.create(name:"Rocket City Rednecks", hulu:false, netflix:false, itunes:2.99, amazon:2.93)
national_geographic.shows.create(name:"Taboo", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
national_geographic.shows.create(name:"The Incredible Dr. Pol", hulu:true, netflix:false , itunes:0, amazon:0)
national_geographic.shows.create(name:"Time Scanners", hulu:true, netflix:true, itunes:2.99, amazon:2.47)
national_geographic.shows.create(name:"Weird or What?", hulu:true, netflix:false, itunes:2.99, amazon:2.99)
nbc.shows.create(name:"A to Z", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
nbc.shows.create(name:"About a Boy", hulu:true, netflix:true, itunes:2.99, amazon:2.99)
nbc.shows.create(name:"America's Got Talent", hulu:true, netflix:false, itunes:2.99, amazon:0)
nbc.shows.create(name:"American Dream Builders", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
nbc.shows.create(name:"American Ninja Warrior", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
nbc.shows.create(name:"Bad Judge", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
nbc.shows.create(name:"Chicago Fire", hulu:true, netflix:true, itunes:2.99, amazon:2.28)
nbc.shows.create(name:"Chicago P.D.", hulu:true, netflix:true, itunes:2.99, amazon:2.99)
nbc.shows.create(name:"Constantine", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
nbc.shows.create(name:"Crossing Lines", hulu:false, netflix:false, itunes:2.99, amazon:3.33)
nbc.shows.create(name:"Dateline NBC", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
nbc.shows.create(name:"Escape Routes", hulu:false, netflix:false, itunes:0, amazon:0)
nbc.shows.create(name:"Fashion Star", hulu:false, netflix:false, itunes:0, amazon:0)
nbc.shows.create(name:"Food Fighters", hulu:false, netflix:false, itunes:0, amazon:0)
nbc.shows.create(name:"Grimm", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
nbc.shows.create(name:"Hannibal", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
nbc.shows.create(name:"Hollywood Game Night", hulu:true, netflix:false, itunes:2.99, amazon:2.98)
nbc.shows.create(name:"Last Call with Carson Daly", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
nbc.shows.create(name:"Last Comic Standing", hulu:true, netflix:false, itunes:2.99, amazon:2.95)
nbc.shows.create(name:"Late Night with Seth Meyers", hulu:false, netflix:false, itunes:0, amazon:0)
nbc.shows.create(name:"Law & Order: Special Victims Unit", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
nbc.shows.create(name:"Love in the Wild", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
nbc.shows.create(name:"Marry Me", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
nbc.shows.create(name:"Minute to Win It", hulu:false, netflix:false, itunes:2.99, amazon:0)
nbc.shows.create(name:"Parenthood", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
nbc.shows.create(name:"Parks and Recreation", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
nbc.shows.create(name:"Running Wild with Bear Grylls", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
nbc.shows.create(name:"Saturday Night Live", hulu:true, netflix:false, itunes:2.99, amazon:1.35)
nbc.shows.create(name:"Stars Earn Stripes", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
nbc.shows.create(name:"State of Affairs", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
nbc.shows.create(name:"The Apprentice", hulu:true, netflix:true, itunes:2.99, amazon:3.99)
nbc.shows.create(name:"The Biggest Loser", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
nbc.shows.create(name:"The Blacklist", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
nbc.shows.create(name:"The Ellen DeGeneres Show", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
nbc.shows.create(name:"The Mysteries of Laura", hulu:true, netflix:false , itunes:2.99, amazon:0)
nbc.shows.create(name:"The Night Shift", hulu:true, netflix:true, itunes:2.99, amazon:2.85)
nbc.shows.create(name:"The Tonight Show Starring Jimmy Fallon", hulu:true, netflix:false , itunes:2.99, amazon:2.95)
nbc.shows.create(name:"The Voice", hulu:true, netflix:false , itunes:2.99, amazon:0)
nbc.shows.create(name:"Undateable", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
netflix.shows.create(name:"Hemlock Grove", hulu:false, netflix:true, itunes:2.99, amazon:2.95)
netflix.shows.create(name:"House of Cards", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
netflix.shows.create(name:"Orange Is the New Black", hulu:false, netflix:true, itunes:2.99, amazon:3.99)
nick.shows.create(name:"Bucket & Skinner's Epic Adventures", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
nick.shows.create(name:"Digimon Fusion", hulu:true, netflix:false, itunes:2.99, amazon:2.99)
nick.shows.create(name:"Dora the Explorer", hulu:false, netflix:false, itunes:2.99, amazon:0)
nick.shows.create(name:"Dragon Ball Z Kai", hulu:true, netflix:true, itunes:2.99, amazon:2.95)
nick.shows.create(name:"Every Witch Way", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
nick.shows.create(name:"Fanboy and Chum Chum", hulu:false, netflix:false, itunes:2.99, amazon:0)
nick.shows.create(name:"Henry Danger", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
nick.shows.create(name:"House of Anubis", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
nick.shows.create(name:"Instant Mom", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
nick.shows.create(name:"Iron Man: Armored Adventures", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
nick.shows.create(name:"Kung Fu Panda: Legends of Awesomeness", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
nick.shows.create(name:"Monsters vs. Aliens", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
nick.shows.create(name:"NFL Rush Zone", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
nick.shows.create(name:"Nicky, Ricky, Dicky & Dawn", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
nick.shows.create(name:"Parental Discretion with Stefanie Wilder-Taylor", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
nick.shows.create(name:"Planet Sheen", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
nick.shows.create(name:"Power Rangers", hulu:true, netflix:true, itunes:2.99, amazon:9.99)
nick.shows.create(name:"Regular Show", hulu:false, netflix:true, itunes:2.99, amazon:2.99)
nick.shows.create(name:"Sanjay and Craig", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
nick.shows.create(name:"Speed Racer: The Next Generation", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
nick.shows.create(name:"SpongeBob SquarePants", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
nick.shows.create(name:"T.U.F.F. Puppy", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
nick.shows.create(name:"Team Umizoomi", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
nick.shows.create(name:"Teenage Mutant Ninja Turtles", hulu:true, netflix:true, itunes:2.99, amazon:1.9)
nick.shows.create(name:"The Fairly OddParents", hulu:true, netflix:true, itunes:2.99, amazon:0)
nick.shows.create(name:"The Haunted Hathaways", hulu:true, netflix:false , itunes:2.99, amazon:2.01)
nick.shows.create(name:"The Legend of Korra", hulu:true, netflix:true, itunes:2.99, amazon:2.49)
nick.shows.create(name:"The Penguins of Madagascar", hulu:true, netflix:true, itunes:2.99, amazon:3.05)
nick.shows.create(name:"The Thundermans", hulu:true, netflix:false , itunes:2.99, amazon:2.99)
nick.shows.create(name:"Voltron Force", hulu:true, netflix:true, itunes:2.99, amazon:2.99)
nick.shows.create(name:"WebHeads", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
nick.shows.create(name:"Wild Grinders", hulu:true, netflix:false, itunes:2.99, amazon:2.99)
own.shows.create(name:"If Loving You Is Wrong", hulu:false, netflix:false, itunes:2.99, amazon:2.99)
own.shows.create(name:"Lindsay", hulu:true, netflix:true, itunes:2.99, amazon:0)
own.shows.create(name:"Love Thy Neighbor", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
own.shows.create(name:"Oprah Presents Master Class", hulu:false, netflix:false, itunes:0, amazon:0)
own.shows.create(name:"Oprah's Lifeclass", hulu:false, netflix:false, itunes:0, amazon:0)
own.shows.create(name:"Oprah's Next Chapter", hulu:false, netflix:false, itunes:0, amazon:0)
own.shows.create(name:"Six Little McGhees", hulu:false , netflix:false , itunes:0, amazon:0)
own.shows.create(name:"The Haves and the Have Nots", hulu:false, netflix:true, itunes:2.99, amazon:2.87)
own.shows.create(name:"Tyler Perry's For Better or Worse", hulu:false, netflix:true, itunes:2.99, amazon:0)
oxygen.shows.create(name:"All the Right Moves", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
oxygen.shows.create(name:"Best Ink", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
oxygen.shows.create(name:"Brooklyn 11223", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
oxygen.shows.create(name:"I'm Having Their Baby", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
oxygen.shows.create(name:"Jersey Couture", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
oxygen.shows.create(name:"My Big Fat Revenge", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
oxygen.shows.create(name:"Snapped", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
oxygen.shows.create(name:"The Bad Girls Club", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
oxygen.shows.create(name:"The Face", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
pbs.shows.create(name:"American Experience", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
pbs.shows.create(name:"American Masters", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
pbs.shows.create(name:"Antiques Roadshow", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
pbs.shows.create(name:"Arthur", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
pbs.shows.create(name:"Austin City Limits", hulu:true, netflix:false, itunes:2.99, amazon:3.99)
pbs.shows.create(name:"Finding Your Roots", hulu:false, netflix:false, itunes:2.99, amazon:2.64)
pbs.shows.create(name:"Frontline", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
pbs.shows.create(name:"Great Performances at the Met", hulu:false, netflix:false, itunes:0, amazon:0)
pbs.shows.create(name:"Great Performances", hulu:false, netflix:false, itunes:2.99, amazon:2.93)
pbs.shows.create(name:"History Detectives", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
pbs.shows.create(name:"Independent Lens", hulu:false, netflix:false, itunes:2.99, amazon:2.99)
pbs.shows.create(name:"Live from the Artists Den", hulu:true, netflix:true, itunes:2.99, amazon:0)
pbs.shows.create(name:"Masterpiece Theatre", hulu:true, netflix:true, itunes:2.99, amazon:0)
pbs.shows.create(name:"Nature", hulu:true, netflix:true, itunes:2.99, amazon:0)
pbs.shows.create(name:"Nova ScienceNow", hulu:true, netflix:true, itunes:2.99, amazon:2.99)
pbs.shows.create(name:"Nova", hulu:true, netflix:true, itunes:2.99, amazon:0)
pbs.shows.create(name:"Pioneers of Television", hulu:false, netflix:true, itunes:2.99, amazon:2.98)
pbs.shows.create(name:"POV", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
pbs.shows.create(name:"Secrets of the Dead", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
pbs.shows.create(name:"Soundstage", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
pbs.shows.create(name:"This Old House", hulu:false, netflix:true, itunes:2.99, amazon:2.99)
pbs.shows.create(name:"Time Team America", hulu:false, netflix:false, itunes:2.99, amazon:2.48)
pbs.shows.create(name:"Voces", hulu:true, netflix:false, itunes:2.99, amazon:2.99)
reelz.shows.create(name:"FanAddicts!", hulu:false, netflix:false, itunes:0, amazon:0.99)
science.shows.create(name:"Build It Bigger", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
science.shows.create(name:"Futurescape", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
science.shows.create(name:"How It's Made", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
science.shows.create(name:"How the Universe Works", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
science.shows.create(name:"Sci Fi Science: Physics of the Impossible", hulu:false, netflix:false , itunes:2.99, amazon:0)
science.shows.create(name:"Through the Wormhole", hulu:true, netflix:true, itunes:2.99, amazon:2.99)
showtime.shows.create(name:"60 Minutes Sports", hulu:false, netflix:false, itunes:0.99, amazon:1.99)
showtime.shows.create(name:"Episodes", hulu:false, netflix:false, itunes:0, amazon:0)
showtime.shows.create(name:"Gigolos", hulu:false, netflix:true, itunes:2.99, amazon:2.81)
showtime.shows.create(name:"Homeland", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
showtime.shows.create(name:"House of Lies", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
showtime.shows.create(name:"Inside Comedy", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
showtime.shows.create(name:"Masters of Sex", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
showtime.shows.create(name:"Next Stop for Charlie", hulu:true, netflix:false, itunes:2.99, amazon:1.9)
showtime.shows.create(name:"Nurse Jackie", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
showtime.shows.create(name:"Oliver Stone's Untold History of United States", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
showtime.shows.create(name:"Penny Dreadful", hulu:false, netflix:false, itunes:2.99, amazon:2.99)
showtime.shows.create(name:"Ray Donovan", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
showtime.shows.create(name:"Shameless", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
showtime.shows.create(name:"The Affair", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
showtime.shows.create(name:"The Green Room", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
showtime.shows.create(name:"The Real L Word", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
showtime.shows.create(name:"Web Therapy", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
showtime.shows.create(name:"Years of Living Dangerously", hulu:true, netflix:false, itunes:2.99, amazon:2.99)
spike.shows.create(name:"Auction Hunters", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
spike.shows.create(name:"Bar Rescue", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
spike.shows.create(name:"Catch a Contractor", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
spike.shows.create(name:"Deadliest Warrior", hulu:false, netflix:true, itunes:2.99, amazon:2.71)
spike.shows.create(name:"Half Pint Brawlers", hulu:false, netflix:true, itunes:2.99, amazon:2.91)
spike.shows.create(name:"Ink Master", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
spike.shows.create(name:"Rat Bastards", hulu:false, netflix:false, itunes:2.99, amazon:2.01)
spike.shows.create(name:"Scrappers", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
spike.shows.create(name:"The Dudesons", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
spike.shows.create(name:"The Ultimate Fighter", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
spike.shows.create(name:"World's Worst Tenants", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
starz.shows.create(name:"Black Sails", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
starz.shows.create(name:"Da Vinci's Demons", hulu:false, netflix:true, itunes:2.99, amazon:2.96)
starz.shows.create(name:"Outlander", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
starz.shows.create(name:"Power", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
starz.shows.create(name:"Survivor's Remorse", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
sundance.shows.create(name:"All on the Line", hulu:false, netflix:false, itunes:0, amazon:0)
sundance.shows.create(name:"Dream School", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
sundance.shows.create(name:"Push Girls", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
sundance.shows.create(name:"Rectify", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
sundance.shows.create(name:"Spectacle: Elvis Costello with ...", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
sundance.shows.create(name:"The Mortified Sessions", hulu:false , netflix:false , itunes:2.99, amazon:0)
sundance.shows.create(name:"The Red Road", hulu:true, netflix:true, itunes:2.99, amazon:1.65)
sundance.shows.create(name:"The Writers' Room", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
sundance.shows.create(name:"Top of the Lake", hulu:true, netflix:false, itunes:2.99, amazon:2.29)
syfy.shows.create(name:"Ascension", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Collection Intervention", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Deep South Paranormal", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Defiance", hulu:true, netflix:true, itunes:2.99, amazon:29.99)
syfy.shows.create(name:"Destination Truth", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Dominion", hulu:true, netflix:false, itunes:2.99, amazon:30.19)
syfy.shows.create(name:"Face Off", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Fact or Faked: Paranormal Files", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Fangasm", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Ghost Hunters", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Ghost Mine", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Haunted Collector", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Haunted Highway", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Haven", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Helix", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Heroes of Cosplay", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Hollywood Treasure", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Hot Set", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Jim Henson's Creature Shop Challenge", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Joe Rogan Questions Everything", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Monster Man", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Paranormal Witness", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Scare Tactics", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"School Spirits", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Stranded", hulu:true, netflix:true, itunes:0, amazon:1.99)
syfy.shows.create(name:"Total Blackout", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
syfy.shows.create(name:"Z Nation", hulu:true, netflix:false, itunes:0, amazon:1.99)
tbs.shows.create(name:"American Dad!", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
tbs.shows.create(name:"Are We There Yet?", hulu:false, netflix:true, itunes:2.99, amazon:2.99)
tbs.shows.create(name:"Conan", hulu:false, netflix:true, itunes:2.99, amazon:0.99)
tbs.shows.create(name:"Cougar Town", hulu:true, netflix:true, itunes:2.99, amazon:2.25)
tbs.shows.create(name:"Ground Floor", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
tbs.shows.create(name:"King of the Nerds", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
tbs.shows.create(name:"Sullivan and Son", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
tbs.shows.create(name:"The Pete Holmes Show", hulu:false, netflix:false , itunes:2.99, amazon:2.49)
tlc.shows.create(name:"19 Kids and Counting", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
tlc.shows.create(name:"Bama Belles", hulu:false, netflix:false, itunes:0, amazon:0)
tlc.shows.create(name:"Breaking Amish", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
tlc.shows.create(name:"Cake Boss", hulu:true, netflix:true, itunes:2.99, amazon:2.81)
tlc.shows.create(name:"Cheer Perfection", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
tlc.shows.create(name:"Craft Wars", hulu:false, netflix:false, itunes:2.99, amazon:0)
tlc.shows.create(name:"DC Cupcakes", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
tlc.shows.create(name:"Extreme Couponing", hulu:false, netflix:false, itunes:2.99, amazon:2.91)
tlc.shows.create(name:"Four Houses", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
tlc.shows.create(name:"Geek Love", hulu:false, netflix:false, itunes:0, amazon:0)
tlc.shows.create(name:"Hoarding: Buried Alive", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
tlc.shows.create(name:"Homemade Millionaire", hulu:false, netflix:false, itunes:0, amazon:0)
tlc.shows.create(name:"LA Ink", hulu:false, netflix:true, itunes:2.99, amazon:1.88)
tlc.shows.create(name:"Little Chocolatiers", hulu:false, netflix:false, itunes:0, amazon:0)
tlc.shows.create(name:"Little People, Big World", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
tlc.shows.create(name:"Long Island Medium", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
tlc.shows.create(name:"My Big Fat American Gyspsy Wedding", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
tlc.shows.create(name:"My Crazy Obsession", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
tlc.shows.create(name:"My Five Wives", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
tlc.shows.create(name:"My Strange Addiction", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
tlc.shows.create(name:"Next Great Baker", hulu:true, netflix:false, itunes:2.99, amazon:0.99)
tlc.shows.create(name:"Say Yes to the Dress Atlanta", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
tlc.shows.create(name:"Say Yes to the Dress", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
tlc.shows.create(name:"Sister Wives", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
tlc.shows.create(name:"The Little Couple", hulu:true, netflix:true, itunes:2.99, amazon:0)
tlc.shows.create(name:"The Sisterhood", hulu:true, netflix:true, itunes:2.99, amazon:0)
tlc.shows.create(name:"Undercover Boss: Abroad", hulu:false, netflix:false, itunes:2.99, amazon:3.28)
tlc.shows.create(name:"What Not to Wear", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
tlc.shows.create(name:"Who Do You Think You Are?", hulu:true, netflix:true, itunes:2.99, amazon:2.33)
tnt.shows.create(name:"Cold Justice", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
tnt.shows.create(name:"Falling Skies", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
tnt.shows.create(name:"Inside Job", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
tnt.shows.create(name:"Legends", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
tnt.shows.create(name:"Major Crimes", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
tnt.shows.create(name:"Murder in the First", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
tnt.shows.create(name:"Perception", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
tnt.shows.create(name:"Private Lives of Nashville Wives", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
tnt.shows.create(name:"Rizzoli & Isles", hulu:true, netflix:true, itunes:2.99, amazon:1.89)
tnt.shows.create(name:"Save Our Business", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
tnt.shows.create(name:"The Hero", hulu:true, netflix:true, itunes:2.99, amazon:2.92)
tnt.shows.create(name:"The Last Ship", hulu:true, netflix:false , itunes:2.99, amazon:1.36)
travel.shows.create(name:"Bizarre Foods with Andrew Zimmern", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
travel.shows.create(name:"Ghost Adventures", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
travel.shows.create(name:"Hotel Impossible", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
travel.shows.create(name:"The Dead Files", hulu:false , netflix:true, itunes:2.99, amazon:1.99)
trutv.shows.create(name:"Caught Red Handed", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
trutv.shows.create(name:"Combat Pawn", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
trutv.shows.create(name:"Conspiracy Theory", hulu:false, netflix:false, itunes:0, amazon:0)
trutv.shows.create(name:"Full Throttle Saloon", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
trutv.shows.create(name:"Hardcore Pawn", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
trutv.shows.create(name:"Hardcore Pawn: Chicago", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
trutv.shows.create(name:"Hot Pursuit", hulu:false, netflix:true, itunes:2.99, amazon:2.99)
trutv.shows.create(name:"Impractical Jokers", hulu:false, netflix:false, itunes:2.99, amazon:2.24)
trutv.shows.create(name:"Lizard Lick Towing", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
trutv.shows.create(name:"Operation Repo", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
trutv.shows.create(name:"South Beach Tow", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
trutv.shows.create(name:"The Smoking Gun Presents: World's Dumbest", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
trutv.shows.create(name:"Upload with Shaquille O'Neal", hulu:false, netflix:false, itunes:2.99, amazon:0)
tv_land.shows.create(name:"Forever Young", hulu:false, netflix:false, itunes:0, amazon:0)
tv_land.shows.create(name:"Harry Loves Lisa", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
tv_land.shows.create(name:"High School Reunion", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
tv_land.shows.create(name:"Hot in Cleveland", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
tv_land.shows.create(name:"She's Got the Look", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
tv_land.shows.create(name:"The Exes", hulu:true, netflix:false , itunes:2.99, amazon:1.99)
tv_land.shows.create(name:"The Soul Man", hulu:true, netflix:false , itunes:2.99, amazon:4.86)
usa.shows.create(name:"Benched", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
usa.shows.create(name:"Chrisley Knows Best", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
usa.shows.create(name:"Covert Affairs", hulu:true, netflix:true, itunes:2.99, amazon:2.99)
usa.shows.create(name:"Graceland", hulu:true, netflix:true, itunes:2.99, amazon:2.8)
usa.shows.create(name:"Playing House", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
usa.shows.create(name:"Royal Pains", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
usa.shows.create(name:"Satisfaction", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
usa.shows.create(name:"Sirens", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
usa.shows.create(name:"Suits", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
usa.shows.create(name:"White Collar", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
vh1.shows.create(name:"Atlanta Exes", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
vh1.shows.create(name:"Basketball Wives", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
vh1.shows.create(name:"Chrissy & Mr. Jones", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
vh1.shows.create(name:"Hit the Floor", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
vh1.shows.create(name:"Hollywood Exes", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
vh1.shows.create(name:"La La's Full Court Wedding", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
vh1.shows.create(name:"Love & Hip Hop", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
vh1.shows.create(name:"Marrying the Game", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
vh1.shows.create(name:"Mob Wives", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
vh1.shows.create(name:"Rock 'n Roll Fantasy Camp", hulu:false, netflix:false, itunes:0, amazon:0)
vh1.shows.create(name:"Scream Queens", hulu:true, netflix:true, itunes:2.99, amazon:2.99)
vh1.shows.create(name:"Single Ladies", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
vh1.shows.create(name:"Stevie TV", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
vh1.shows.create(name:"That Metal Show", hulu:false, netflix:false , itunes:2.99, amazon:1.99)
vh1.shows.create(name:"You're Cut Off", hulu:false, netflix:false, itunes:2.99, amazon:0)
we.shows.create(name:"Braxton Family Values", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
we.shows.create(name:"Bridezillas", hulu:false, netflix:true, itunes:2.99, amazon:1.99)
we.shows.create(name:"I Do Over", hulu:false, netflix:false, itunes:2.99, amazon:2.99)
we.shows.create(name:"My Fair Wedding", hulu:true, netflix:false, itunes:2.99, amazon:1.99)
we.shows.create(name:"The Divide", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
we.shows.create(name:"The Locator", hulu:false , netflix:true, itunes:2.99, amazon:7.89)
wgn.shows.create(name:"Manhattan", hulu:true, netflix:true, itunes:2.99, amazon:1.99)
wgn.shows.create(name:"Salem", hulu:false, netflix:false, itunes:2.99, amazon:1.99)
